spring:
  application:
    name: weekly-tasks-backend

  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true

server:
  port: 8080

cors:
  allowed-origins: http://localhost:4200

logging:
  level:
    com.tibia: DEBUG
    org.springframework.data.mongodb: DEBUG
